[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GMT = "5752ebe1-31b9-557e-87aa-f909b540aa54"
Parquet2 = "98572fba-bba0-415d-956f-fa77e587d26d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
